// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_sAvj5Us_QCCFyVHBzeVhUO0D-971hB8',
    appId: '1:647887302854:android:424dae7183ec67389c27c7',
    messagingSenderId: '647887302854',
    projectId: 'finanzas-d7be1',
    storageBucket: 'finanzas-d7be1.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsri5e3XMhYdsy_ezLAdHAHyXw8ZeN_6s',
    appId: '1:647887302854:web:e94df4ca040402b99c27c7',
    messagingSenderId: '647887302854',
    projectId: 'finanzas-d7be1',
    authDomain: 'finanzas-d7be1.firebaseapp.com',
    storageBucket: 'finanzas-d7be1.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwQiiNVu123Zc0VoDDwVx17nfNj6teKkM',
    appId: '1:647887302854:ios:468bffe4b6766c9b9c27c7',
    messagingSenderId: '647887302854',
    projectId: 'finanzas-d7be1',
    storageBucket: 'finanzas-d7be1.appspot.com',
    iosBundleId: 'com.example.finanzas',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwQiiNVu123Zc0VoDDwVx17nfNj6teKkM',
    appId: '1:647887302854:ios:468bffe4b6766c9b9c27c7',
    messagingSenderId: '647887302854',
    projectId: 'finanzas-d7be1',
    storageBucket: 'finanzas-d7be1.appspot.com',
    iosBundleId: 'com.example.finanzas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsri5e3XMhYdsy_ezLAdHAHyXw8ZeN_6s',
    appId: '1:647887302854:web:54a5b0c30f88ced59c27c7',
    messagingSenderId: '647887302854',
    projectId: 'finanzas-d7be1',
    authDomain: 'finanzas-d7be1.firebaseapp.com',
    storageBucket: 'finanzas-d7be1.appspot.com',
  );

}